# examples/valid/deployment-with-probes.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: valid-nginx
  labels:
    app: nginx
    # environment: production
    # team: platform
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: praveenbsd/nginx:latest
        resources:
          # limits:
          #   cpu: "500m"
          #   memory: "512Mi"
          requests:
            cpu: "200m"
            memory: "256Mi"
        # Uncomment the below lines to enable probes
        # livenessProbe:
        #   httpGet:
        #     path: /
        #     port: 80
        #   initialDelaySeconds: 10
        #   periodSeconds: 10
        # readinessProbe:
        #   httpGet:
        #     path: /
        #     port: 80
        #   initialDelaySeconds: 5
        #   periodSeconds: 5