# restrict-image-registry.yaml
apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: restrict-image-registry
  annotations:
    policies.kyverno.io/title: Restrict Image Registry
    policies.kyverno.io/category: Security
    policies.kyverno.io/severity: high
    policies.kyverno.io/description: >-
      Only allow container images from praveenbsd Docker Hub repository.
spec:
  validationFailureAction: enforce
  background: true
  rules:
    - name: verify-registry
      match:
        any:
        - resources:
            kinds:
            - Deployment
            - Pod
            - StatefulSet
            - DaemonSet
      validate:
        message: "Container images must be from docker.io/praveenbsd/ repository only"
        pattern:
          spec:
            template:
              spec:
                containers:
                  - image: "praveenbsd/*"